### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by admshao** [GamesDoneQuick/agdq16-layouts#9]
Tried with NodeCG 0.7.0 - 0.7.7 and 0.8.0 and all of them i had problem with tried to node index.js

All had issues with Observe.observe. Running on Node 6.1.0 and NPM 3.8.6

Running Ubuntu 16.04, Kernel 4.5.3

**Comment by Lange** [comment]
NodeCG v0.7 and prior cannot run on Node.js v6. Use Node.js v5 or earlier.

Additionally, this bundle cannot run on NodeCG v0.8.

**Comment by admshao** [comment]
Thanks for the very quickly response! Node v5 did the trrick!
